"""Prompt templates for RAG system."""

from .templates import (
    INSTRUCTIONS_ANSWER_JSON,
    RAG_PROMPT,
    BASELINE_PROMPT,
    SELF_REFINEMENT_PROMPT,
    REFINE_FROM_ISSUES_PROMPT,
    INSTRUCTIONS_CRITIQUE_JSON,
    CRITIC_PROMPT,
)

__all__ = [
    "INSTRUCTIONS_ANSWER_JSON",
    "RAG_PROMPT",
    "BASELINE_PROMPT",
    "SELF_REFINEMENT_PROMPT",
    "REFINE_FROM_ISSUES_PROMPT",
    "INSTRUCTIONS_CRITIQUE_JSON",
    "CRITIC_PROMPT",
]
